name: ToolboxLib Update Native-Nuget-Dependabotwrapper

on:
  push:
    branches: [ "main", "integrate-native-nuget-scanning-project" ]
    paths:
      - ToolboxLib/packages.config
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: p

    - name: Checkout sgrottel/native-nuget-dependabot
      uses: actions/checkout@v4
      with:
        repository: sgrottel/native-nuget-dependabot
        path: nnd
        token: ${{ secrets.DOPINDERBOT_PAT }}

    - name: Update action
      shell: pwsh
      run: |
        .\nnd\Set-Project.ps1 -projFile "p\ToolboxLib\ToolboxLib.vcxproj" -group "open-here" -name "ToolboxLib" -info "https://github.com/sgrottel/open-here"

        cd .\nnd
        git config --global user.name 'DopinderBot'
        git config --global user.email 'DopinderBot-noreply@sgrottel.de'
        git commit -am "Updated open-here ToolboxLib"
        git push
        cd ..
